package com.aloksharma.hisaab

enum class Lang { HI, EN }

/** Hindi is the default. The register is colloquial, the way people actually talk about money. */
data class Strings(
    val title: String,
    val tagline: String,
    val privateMode: String,
    val privateModeBody: String,
    val txnCount: String,
    val dailyAvg: String,
    val biggest: String,
    val demoMode: String,
    val demoModeBody: String,
    val spent: String,
    val received: String,
    val net: String,
    val byCategory: String,
    val recent: String,
    val empty: String,
    val grantTitle: String,
    val grantBody: String,
    val grantButton: String,
    val granted: String,
    val simulate: String,
    val needsReview: String,
    val tabLedger: String,
    val tabStats: String,
    val tabSettings: String,
    val settingsAccess: String,
    val accessOn: String,
    val accessOff: String,
    val manageAccess: String,
    val privacyTitle: String,
    val privacyBody: String,
    val noStats: String,
    val thisMonth: String,
    val topMerchants: String,
    val today: String,
    val yesterday: String,
    val categories: Map<Category, String>,
) {
    companion object {
        fun of(lang: Lang) = if (lang == Lang.HI) HI else EN

        private val HI = Strings(
            title = "हिसाब",
            tagline = "पेमेंट का हिसाब, अपने आप",
            privateMode = "नाम और रकम छुपाएँ",
            privateModeBody = "किसी के सामने ऐप खोलनी पड़े तो नाम और रकम तारों में बदल जाते हैं। डेटा वैसा ही रहता है, बस दिखता नहीं।",
            txnCount = "लेन-देन",
            dailyAvg = "रोज़ औसत",
            biggest = "सबसे बड़ा खर्च",
            demoMode = "डेमो डेटा",
            demoModeBody = "दिखाने के लिए बनाया हुआ महीने भर का खर्च। आपका असली हिसाब वैसा ही रहता है, छुआ तक नहीं जाता।",
            spent = "खर्च",
            received = "मिला",
            net = "नेट बदलाव",
            byCategory = "किस चीज़ पर",
            recent = "हाल के लेन-देन",
            empty = "अभी कुछ नहीं। नोटिफिकेशन की अनुमति दे दीजिए, फिर हर पेमेंट खुद यहाँ आ जाएगी।",
            grantTitle = "नोटिफिकेशन की अनुमति चाहिए",
            grantBody = "हिसाब आपके UPI और बैंक ऐप की नोटिफिकेशन पढ़कर खर्च जोड़ता है। " +
                "सब कुछ फ़ोन में ही रहता है, कहीं नहीं जाता। SMS कभी नहीं पढ़ा जाता।",
            grantButton = "अनुमति दें",
            granted = "अनुमति मिल गई",
            simulate = "डेमो पेमेंट डालें",
            needsReview = "जाँच लें",
            tabLedger = "हिसाब",
            tabStats = "आँकड़े",
            tabSettings = "सेटिंग",
            settingsAccess = "नोटिफिकेशन एक्सेस",
            accessOn = "चालू है",
            accessOff = "बंद है",
            manageAccess = "सेटिंग खोलें",
            privacyTitle = "आपका डेटा कहाँ जाता है",
            privacyBody = "कहीं नहीं। इस ऐप के पास इंटरनेट की अनुमति ही नहीं है, इसलिए डेटा फ़ोन से बाहर जा ही नहीं सकता। कोई अकाउंट नहीं, कोई सर्वर नहीं। जो नोटिफिकेशन लेन-देन नहीं है, वह पढ़कर तुरंत छोड़ दी जाती है।",
            noStats = "आँकड़े दिखाने के लिए अभी कोई खर्च नहीं है।",
            thisMonth = "इस महीने",
            topMerchants = "सबसे ज़्यादा कहाँ",
            today = "आज",
            yesterday = "कल",
            categories = mapOf(
                Category.FOOD to "खाना",
                Category.GROCERIES to "राशन",
                Category.FUEL to "पेट्रोल",
                Category.TRANSPORT to "सफ़र",
                Category.BILLS to "बिल",
                Category.SHOPPING to "खरीदारी",
                Category.HEALTH to "सेहत",
                Category.RENT to "किराया",
                Category.TRANSFER to "ट्रांसफर",
                Category.INCOME to "इनकम",
                Category.OTHER to "बाकी",
            ),
        )

        private val EN = Strings(
            title = "Hisaab",
            tagline = "Your payments, logged by themselves",
            privateMode = "Hide names and amounts",
            privateModeBody = "Names and amounts turn into asterisks when you have to open the app in front of someone. The data is unchanged, it just stops showing.",
            txnCount = "Transactions",
            dailyAvg = "Daily average",
            biggest = "Biggest expense",
            demoMode = "Demo data",
            demoModeBody = "A made-up month of spending, for showing the app. Your real ledger is left exactly as it is.",
            spent = "Spent",
            received = "Received",
            net = "Net change",
            byCategory = "Where it went",
            recent = "Recent transactions",
            empty = "Nothing yet. Grant notification access and every payment lands here on its own.",
            grantTitle = "Notification access needed",
            grantBody = "Hisaab reads your UPI and bank app notifications to build the ledger. " +
                "Everything stays on this phone. SMS is never read.",
            grantButton = "Grant access",
            granted = "Access granted",
            simulate = "Add demo payment",
            needsReview = "Check",
            tabLedger = "Ledger",
            tabStats = "Stats",
            tabSettings = "Settings",
            settingsAccess = "Notification access",
            accessOn = "On",
            accessOff = "Off",
            manageAccess = "Open settings",
            privacyTitle = "Where your data goes",
            privacyBody = "Nowhere. The app holds no internet permission at all, so data cannot leave this phone even in principle. No account, no server. Any notification that is not a transaction is read and dropped, never stored.",
            noStats = "No spending to chart yet.",
            thisMonth = "This month",
            topMerchants = "Biggest merchants",
            today = "Today",
            yesterday = "Yesterday",
            categories = mapOf(
                Category.FOOD to "Food",
                Category.GROCERIES to "Groceries",
                Category.FUEL to "Fuel",
                Category.TRANSPORT to "Transport",
                Category.BILLS to "Bills",
                Category.SHOPPING to "Shopping",
                Category.HEALTH to "Health",
                Category.RENT to "Rent",
                Category.TRANSFER to "Transfer",
                Category.INCOME to "Income",
                Category.OTHER to "Other",
            ),
        )
    }
}

/**
 * Track 4: an emulator receives no real bank notifications, so the demo feeds these through
 * the same LedgerRepository.ingest() the live listener uses. Three different source formats
 * so the demo shows the parser is not hardcoded to one app.
 */
val DEMO_NOTIFICATIONS: List<Pair<String, String>> = listOf(
    "com.google.android.apps.nbu.paisa.user" to "Google Pay You paid ₹850 to Zomato",
    "com.phonepe.app" to "PhonePe Payment of ₹240 to Rapido successful",
    "com.snapwork.hdfc" to "HDFC Bank Rs.1,200.00 credited to A/c XX4412 by VPA rahul.s@okhdfc on 20-09-26",
    "net.one97.paytm" to "Paytm ₹499 paid to Amazon using UPI",
    "com.sbi.yono" to "SBI Rs 320.00 debited from A/c XX7781 to VPA indianoil@ybl on 20-09-26 Ref 5544",
)
